[spider]
SPIDER_RES_DIR = "./result/spider/"
SPIDER_IMAGE_DIR = "./result/img/"

[novel]
NOVEL_INDEX=2                # 选择第几本书
NOVEL_THREAD_NUM=1           # 读取小说线程数
NOVEL_CHAPTER_CONSTANT=true  # 是否章节连续
NOVEL_WEBSITE=[
    # "https://blog.xbookcn.net/search/label/"
    "https://book.xbookcn.net",
    "https://www.bbiquge.net",
    "https://www.92qb.com/",
]
NOVEL_BASE_URL=[
    "https://book.xbookcn.net/search/label/",
    "",
    "https://www.92qb.com/xiaoshuo",
]
NOVEL_DIR=[
    "./result/novel/xbook/",
    "./result/novel/biquge/",
    "./result/novel/92qb/",
]
NOVEL_RESULT_JSON_PATH=[
    # "./result/spider/novel.short.json",
    "./result/spider/novel.92qb.json",
    "./result/spider/novel.biquge.json",
    "./result/spider/novel.92qb.json",
]
## xbook
# NOVEL_URL_CHAPTER_APPEND="?max-results=200&by-date=false"
# NOVEL_NAME=[
# ]
# NOVEL_URL=[
# ]
## 笔趣阁
# NOVEL_WEBSITE="https://www.bbiquge.net"
# NOVEL_NAME=[
# ]
# NOVEL_URL=[
#     "https://www.bbiquge.net/book_132488/",
# ]
## 92qb.com
NOVEL_NAME=[
    "奇门遁甲",
]
NOVEL_URL=[
    "/3/3468/"
]


[javdisk]
# javdisk.com封面网站
JAV_COVER_URL=[
    "https://javdisk.com/"
]
IMG_DIR="/JAV/"